[package]
name = "penguin_coin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "coin"
test = true

[dependencies]
clap = { version = "3.0.1", features = ["derive"] }
thiserror = "1.0.30"